### PR TITLE
actions/setup-ssh: Direct access to runner machines over Tailscale

### PR DESCRIPTION
**Pull request by tsibley**
Useful for debugging issues with GitHub Actions workflows, particularly in cases when similar commands work on your machine but not the runner machines.

See also [the README](https://github.com/nextstrain/.github/blob/actions/setup-ssh/actions/setup-ssh/README.md).

### Related issue(s)

- https://github.com/nextstrain/private/pull/72

### Testing

- [x] Manual testing
- [x] Checks pass

### CODE REVIEW

**Comment by tsibley** [comment]
Note that I haven't (yet) defined a `TAILSCALE_AUTH_KEY` secret at any level (repo or org), because some internal discussion is probably warranted about the account to use and how to best share access to the team before I set things up. However, I have used single-use ephemeral auth keys for my personal Tailscale account to test https://github.com/nextstrain/private/pull/72.

**Comment by tsibley** [comment]
To personally test this, you'll need:

- At least one [SSH key associated with your GitHub user](https://github.com/settings/keys)
- A personal [Tailscale account](https://login.tailscale.com/start)

Steps:

1. [Generate a **single-use** and **ephemeral** Tailscale auth key
](https://login.tailscale.com/admin/settings/keys)
2. [Launch the `debugging-runner` workflow in our nextstrain/private repo](https://github.com/nextstrain/private/actions/workflows/debugging-runner.yaml), providing the auth key as an input.
3. Follow logs from the run and look for output like `ssh runner@100.x.y.z`
4. Use it to login! Tailscale must be installed and running on your computer.

**Comment by tsibley** [comment]
I was using this again on Friday to try out commands on a runner while adding [the Singularity runtime](https://github.com/nextstrain/cli/pull/248) to Nextstrain CLI's CI. Since it's working well for me and there's zero consequence right now if it doesn't, I'm going to merge this. That will let me address https://github.com/nextstrain/private/pull/72#discussion_r1052611618.

We can address providing an org-level Tailscale auth key (per https://github.com/nextstrain/.github/pull/34#issuecomment-1358263734) separately.

**Review by victorlin — COMMENTED** [review]
Thanks for setting this up! Works for me. Made a few changes over at https://github.com/nextstrain/private/compare/93cfadce8e28580c868576d6e3d980b9c99c09fe...4a5756f450d0a56e26ea4cde6981d4bd3df9a83b based on my experience.

**Pull request merged**
